import { useState } from 'react'
import api from '../api/axios'
import toast from 'react-hot-toast'
import jsPDF from 'jspdf'
import useLanguages from '../hooks/useLanguages'

export default function SummarizePage() {
  const LANGUAGES = useLanguages()
  const [fileId, setFileId] = useState(localStorage.getItem('last_file_id') || '')
  const [language, setLanguage] = useState(localStorage.getItem('preferred_language') || 'english')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)

  const handleSummarize = async () => {
    if (!fileId.trim()) return toast.error('Please enter a File ID!')
    setLoading(true)

    const toastId = toast.loading('Analyzing medical report...')

    try {
      const res = await api.post('/summarize', { file_id: fileId, language })
      setResult(res.data)
      toast.success('Report analyzed!', { id: toastId })
    } catch (err) {
      toast.error(err.response?.data?.detail || 'Failed to analyze report', { id: toastId })
    } finally {
      setLoading(false)
    }
  }

  const exportTxt = () => {
    if (!result) return
    const content = `
MEDIASSIST AI - MEDICAL REPORT SUMMARY
=======================================
Generated: ${new Date().toLocaleString()}

PATIENT NAME: ${result.patient_name}
DIAGNOSIS: ${result.diagnosis}
SUMMARY: ${result.full_summary}

ABNORMAL VALUES:
${result.abnormal_values?.map(v => `• ${v}`).join('\n') || 'None'}

RECOMMENDATIONS:
${result.recommendations?.map(r => `• ${r}`).join('\n') || 'None'}

=======================================
This is an AI-generated summary. Always consult a doctor.
    `.trim()

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `Medical-Summary-${result.patient_name}-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
    toast.success('Exported as .txt')
  }

  const exportPdf = () => {
    if (!result) return
    const doc = new jsPDF({ unit: 'pt', format: 'a4' })
    const marginX = 44
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const maxWidth = pageWidth - marginX * 2
    let y = 56

    const heading = (text, size = 12) => {
      if (y > pageHeight - 60) { doc.addPage(); y = 56 }
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(size)
      doc.setTextColor(20)
      doc.text(text, marginX, y)
      y += size + 6
    }

    const paragraph = (text) => {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10.5)
      doc.setTextColor(40)
      const lines = doc.splitTextToSize(text || 'Not found', maxWidth)
      lines.forEach(line => {
        if (y > pageHeight - 50) { doc.addPage(); y = 56 }
        doc.text(line, marginX, y)
        y += 14
      })
      y += 8
    }

    const bulletList = (items) => {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10.5)
      doc.setTextColor(40)
      if (!items || items.length === 0) {
        paragraph('None')
        return
      }
      items.forEach(item => {
        const lines = doc.splitTextToSize(`•  ${item}`, maxWidth)
        lines.forEach(line => {
          if (y > pageHeight - 50) { doc.addPage(); y = 56 }
          doc.text(line, marginX, y)
          y += 14
        })
      })
      y += 8
    }

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.setTextColor(20)
    doc.text('Medical Report Summary', marginX, y)
    y += 20
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(120)
    doc.text(`Generated by MediAssist AI • ${new Date().toLocaleString()}`, marginX, y)
    y += 28

    heading('Patient Name')
    paragraph(result.patient_name)

    heading('Diagnosis')
    paragraph(result.diagnosis)

    heading('Summary')
    paragraph(result.full_summary)

    heading('Abnormal Values')
    bulletList(result.abnormal_values)

    heading('Recommendations')
    bulletList(result.recommendations)

    if (y > pageHeight - 60) { doc.addPage(); y = 56 }
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(9)
    doc.setTextColor(150)
    doc.text('This is an AI-generated summary. Always consult a doctor.', marginX, pageHeight - 30)

    doc.save(`Medical-Summary-${result.patient_name}-${Date.now()}.pdf`)
    toast.success('Exported as PDF')
  }

  return (
    <div className="max-w-2xl mx-auto animate-fadeIn">

      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-black text-gray-900 dark:text-white">Summarize Report</h2>
          <p className="text-gray-500 dark:text-slate-400 text-sm">AI extracts key medical information</p>
        </div>
        {result && (
          <div className="flex gap-2">
            <button onClick={exportPdf}
              className="bg-green-600 text-white px-4 py-2 rounded-xl text-sm font-medium hover:bg-green-700 transition-all">
              📄 PDF
            </button>
            <button onClick={exportTxt}
              className="bg-gray-100 dark:bg-white/10 text-gray-700 dark:text-slate-300 px-4 py-2 rounded-xl text-sm font-medium hover:bg-gray-200 dark:hover:bg-white/20 transition-all">
              TXT
            </button>
          </div>
        )}
      </div>

      <div className="mb-4 flex gap-2">
        <div className="flex-1">
          <label className="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-1">File ID</label>
          <input
            type="text"
            value={fileId}
            onChange={e => { setFileId(e.target.value); localStorage.setItem('last_file_id', e.target.value) }}
            placeholder="e.g. a1b2c3d4"
            className="w-full border border-gray-300 dark:border-white/10 bg-white dark:bg-white/5 text-gray-800 dark:text-slate-200 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400 placeholder-gray-400"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-1">Language</label>
          <select value={language}
            onChange={e => { setLanguage(e.target.value); localStorage.setItem('preferred_language', e.target.value) }}
            className="border border-gray-300 dark:border-white/10 bg-white dark:bg-white/5 text-gray-800 dark:text-slate-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400">
            {LANGUAGES.map(l => <option key={l.value} value={l.value}>{l.label}</option>)}
          </select>
        </div>
      </div>

      <button
        onClick={handleSummarize}
        disabled={loading || !fileId.trim()}
        className="w-full bg-purple-600 text-white py-3 rounded-xl font-semibold hover:bg-purple-700 disabled:opacity-50 transition-all shadow-lg"
      >
        {loading ? 'Analyzing...' : 'Summarize Report'}
      </button>

      {loading && (
        <div className="mt-6 space-y-3">
          {[...Array(4)].map((_, i) => (
            <div key={i} className="skeleton h-16 w-full"></div>
          ))}
        </div>
      )}

      {result && (
        <div className="mt-4 space-y-3 animate-fadeIn">
          {[
            { label: 'Patient Name', value: result.patient_name, color: 'border-l-blue-500' },
            { label: 'Diagnosis', value: result.diagnosis, color: 'border-l-purple-500' },
            { label: 'Summary', value: result.full_summary, color: 'border-l-green-500' },
          ].map(item => (
            <div key={item.label} className={`bg-white dark:bg-white/5 border border-gray-100 dark:border-white/10 border-l-4 ${item.color} rounded-xl p-4 shadow-sm`}>
              <p className="text-xs font-bold text-gray-400 uppercase tracking-wide mb-1">{item.label}</p>
              <p className="text-gray-800 dark:text-slate-200">{item.value}</p>
            </div>
          ))}

          {result.abnormal_values?.length > 0 && (
            <div className="bg-red-50 dark:bg-red-500/10 border border-red-200 dark:border-red-500/20 border-l-4 border-l-red-500 rounded-xl p-4">
              <p className="text-sm font-bold text-red-600 dark:text-red-400 mb-2">Abnormal Values</p>
              <ul className="space-y-1">
                {result.abnormal_values.map((v, i) => (
                  <li key={i} className="text-sm text-red-700 dark:text-red-300 flex items-center gap-2">
                    <span className="w-1.5 h-1.5 bg-red-500 rounded-full"></span>{v}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {result.recommendations?.length > 0 && (
            <div className="bg-green-50 dark:bg-green-500/10 border border-green-200 dark:border-green-500/20 border-l-4 border-l-green-500 rounded-xl p-4">
              <p className="text-sm font-bold text-green-700 dark:text-green-400 mb-2">Recommendations</p>
              <ul className="space-y-1">
                {result.recommendations.map((r, i) => (
                  <li key={i} className="text-sm text-green-700 dark:text-green-300 flex items-center gap-2">
                    <span className="w-1.5 h-1.5 bg-green-500 rounded-full"></span>{r}
                  </li>
                ))}
              </ul>
            </div>
          )}

          <button onClick={exportPdf}
            className="w-full bg-green-600 text-white py-3 rounded-xl font-semibold hover:bg-green-700 transition-all">
            📄 Export Summary as PDF
          </button>
          <p className="text-xs text-center text-gray-400">This is an AI-generated summary — always consult a real doctor</p>
        </div>
      )}
    </div>
  )
}